---
- name: Format the device with Btrfs
  filesystem:
    fstype: btrfs
    dev: "{{ btrfs_device }}"

- name: Create the mount point
  file:
    path: "{{ time_machine_dir }}"
    state: directory

- name: Mount the device
  mount:
    path: "{{ time_machine_dir }}"
    src: "{{ btrfs_device }}"
    fstype: btrfs
    opts: defaults,autodefrag,compress=zstd
    state: mounted
